runtime: python39  # Use python38 or python311 if needed

entrypoint: gunicorn -b :$PORT app:app  # Replace 'app' with your Python filename

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
